project:
  type: website

website:
  title: "Central Limit"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/sh-nishonov
      
format:
  html:
    theme: cosmo
    css: styles.css



